#!/usr/bin/env python
"""
Manage.py entry point for the CRM project.

This script sets the DJANGO_SETTINGS_MODULE environment variable to point
to the correct settings file and then executes Django's command-line
utility. It is a thin wrapper around django-admin and mirrors the
default manage.py generated by Django.

Note: Django must be installed in your environment for this script to
function properly. See README.md for installation instructions.
"""

import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()