# Generated by Django 4.2.27 on 2025-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('listed', 'Listed'), ('sold', 'Sold'), ('let', 'Let')], default='listed', max_length=30),
        ),
    ]
